### ISSUE TITLE
additional information for defineStreamHandler

### ISSUE THREAD

**Issue by postnikovmaksim** [Stremio/stremio-addon-sdk#105]
In accordance with the documentation, information about the identifier and type comes to the method only. Can I still somehow get information about the name of the film and the year without making a request for an external resource?

**Comment by Ivshti** [comment]
Not from the arguments. You need to find a way to associate the ID to a name. A good idea is to use Cinemeta: https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/advanced.md#getting-metadata-from-cinemeta

**Comment by jaruba** [comment]
I've added a note about getting additional metadata for the requested item on the `defineStreamHandler` doc page: https://github.com/Stremio/stremio-addon-sdk/commit/02b6a4dcd4d69214cc0d522b996f72879f9cb61d
