### ISSUE TITLE
Possible typo in manifest documentation

### ISSUE THREAD

**Issue by sleeyax** [Stremio/stremio-addon-sdk#109]
Reading the [manifest](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/manifest.md#extra-properties) docs:

> if your catalog supports filtering by genre, set extra: [{ name: "genre", isRequired: false }].

And a bit further, where the `extra` format is explained:
>  where you need the user to select from a pre-set list of options (e.g. { name: "genres", options: ["Action", "Comedy", "Drama"] }

Is it `genre`, `genres`, both or a typo?

**Comment by Ivshti** [comment]
Im pretty sure it's `genre` in both cases

@jaruba can you confirm and fix?
