### ISSUE TITLE
Is behaviorHints.group implemented?

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-addon-sdk#121]
I've tried to use it in the stream object, with some unique identifier to play the next episode, but it didn't work and the first stream entry started to play next.

Linux Manjaro
Stremio 4.4.77
WebUI 4.4.108
Server 4.6.0

**Comment by Ivshti** [comment]
AFAIK it's not implemented in the desktop app/android but it is in stremio-web. @jaruba @nklhrstv? this may be pretty easy to implement in the desktop/mobile apps, we just have to tweak open.js in stremio-models

**Comment by dexter21767-dev** [comment]
this option has been implemented across all platforms, under stream.behaviorHints.bingeGroup .
please refer to the [docs](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md#additional-properties-to-provide-information--behaviour-flags).
