### ISSUE TITLE
Addon Settings

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-addon-sdk#125]
We've been discussing addon settings and how they should be implemented.

There are 2 cases:

- an addon can have settings, yet also be installed without any settings
- an addon requires settings, and cannot be installed without configuring it

This task presumes adding 2 new `behaviorHints` to the manifest:
```
manifest {
    behaviorHints: {
        configurable: true,
        configurationRequired: true
    }
}
```

In the SDK, we will need to document these 2 properties, while also giving a way to generate a settings page based on the addon developer's requirements.

A good example of how we could generate a settings page (using the path: `/configure`) could be found in PimpMyStremio's (community project) handling of this requirement:
https://github.com/sungshon/PimpMyStremio/blob/master/docs/README.md#user-settings

Additionally, `behaviorHints.configurationRequired` should be removed from the manifest in the case that the addon has already been configured (based on the addon URL path), as otherwise `stremio-core` will reject the addon installation.

**Comment by doingodswork** [comment]
This would be extremely useful. Giving my +1 for eagerly looking forward to this feature!

**Comment by doingodswork** [comment]
For others looking for more info about this, here are already some example addons that make use of this feature: https://github.com/Stremio/stremio-web/issues/174

**Comment by jaruba** [comment]
Addon settings are now also supported in the new Android release: v1.3.0

**Comment by Dmjwauzi** [comment]
my streams are not found 
help me please
