### ISSUE TITLE
Stream handler not being called

### ISSUE THREAD

**Issue by samuelpetroline** [Stremio/stremio-addon-sdk#126]
Hi guys, how are you doing?

I've been pounding my head on this for a while now and I can't get around it. Basically, my stream handler is never called. All the others are ok.

My code: https://github.com/samuelpetroline/stremio-archive.org-addon

My manifest:

```js
const manifest = {
	'id': 'stremio.archive.org.addon',
	'version': '1.0.0',
	'name': 'Archive.org Movies',
	'description': 'Public domain movies available on Archive.org',
	'resources': ['catalog', {
		name: 'meta',
		types: ['movie'],
		idPrefixes: [env.addonContentIdPrefix]
	},{
		name: 'stream',
		types: ['movie'],
		idPrefixes: [env.addonContentIdPrefix]
	}],
	'types': ['movie'],
	'catalogs': [{
		type: 'movie',
		id: 'archive-org.movies',
		name: 'Archive.org movies',
		extra: [{
			name: 'search',
			isRequired: false
		}, {
			name: 'genre',
			isRequired: false
		}, {
			name: 'skip',
			isRequired: false
		}]
	}]
}
```

Is there anything different that needs to be done for this specific handler?

Thanks in advance

**Comment by Ivshti** [comment]
It should be called, just keep in mind it will only be called for items with start with `env.addonContentIdPrefix`

**Comment by samuelpetroline** [comment]
After removing the `idPrefixes: [env.addonContentIdPrefix]` it worked. Not the best solution but one that suits me for now. Thanks!
