### ISSUE TITLE
fileIdx not working on streams

### ISSUE THREAD

**Issue by domejuanan** [Stremio/stremio-addon-sdk#127]
I developed an small addon for myself and I am sending to the stremio client the next JSON

`{
	"streams": [
		{
			"name": "VOSE",
			"title": "PACK.S01.WEBRip 2.01 GBs S:117 L:25",
			"infoHash": "5cfd9c473c13927fe4210e504afb6414a5c7a3a5",
			"fileIdx": "4"
		},
		{
			"name": "VOSE",
			"title": "PACK.S01.1080p.WEBRip 8.35 GBs S:81 L:37",
			"infoHash": "58fb757580a28753fe41f17d411a780464ad2d8d",
			"fileIdx": "4"
		},
		{
			"name": "VOSE",
			"title": "PACK.S01.720p.WEBRip 5.08 GBs S:43 L:12",
			"infoHash": "48cb6bcc681bd50c08bac5fbd8345a1f76a0a2a6",
			"fileIdx": "4"
		}
	]
}`

When I click on one of the torrents it ignores the fileIdx number and always plays the same file.

Is there something I am not doing properly ?

Regards

**Comment by Ivshti** [comment]
yes, serving it as a string rather than a number 

You need to deliver a 4, rather than a "4"

**Comment by domejuanan** [comment]
Ok, silly mistake.

Thank you very much.

Regards
