### ISSUE TITLE
How do I update the url of an addon?

### ISSUE THREAD

**Issue by luisfranciscocesar** [Stremio/stremio-addon-sdk#136]
I used this url to publish my addon, but I want to change the url, how do I do it?
https://stremio.github.io/stremio-publish-addon/index.html

**Comment by sleeyax** [comment]
Just change the url and publish your addon again. AFAIK as long as you use the same id and increment the version it will auto-update for users.

**Comment by jaruba** [comment]
I'm closing this as @sleeyax 's answer is correct
