### ISSUE TITLE
Meta video not shown if video ID matches meta ID

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-addon-sdk#143]
Not sure if that's intended behavior or not, but when a video entry has the same ID as the meta itself, the video episode is not shown in the desktop UI, but it seems to work fine on Android.

**Comment by Ivshti** [comment]
By spec, future Stremio versions should treat this case like this: not show the videos selector UI, but directly show the streams for that video - like movies do currently

Do streams load directly? If not - it's probably a bug  

cc @jaruba @TRtomasz

**Comment by TheBeastLT** [comment]
No, streams do not load. On android, the episode is shown and when you click on it it load the streams.

**Comment by TheBeastLT** [comment]
Were you able to replicate or solve this?

**Comment by jaruba** [comment]
@TheBeastLT i will try to reproduce it tomorrow, if it is really a bug we'll also try to fix it tomorrow, thank you for reminding us of it

**Comment by jaruba** [comment]
@TheBeastLT i created a test addon for this case, please confirm that this is the expected meta response that should reproduce it:
https://1fe84bc728af-test-mixed-released.baby-beamup.club/videoIdSameAsMetaId/meta/series/trvalue_1.json

Notice the second video object entitles "Same as Meta ID" has the same ID as the meta object.

**Comment by TheBeastLT** [comment]
@jaruba No, that's not correct. The meta should have only a single video with ID same as meta ID.

**Comment by jaruba** [comment]
@TheBeastLT ok, i removed all other video objects except the one with the same id as the meta id:
https://1fe84bc728af-test-mixed-released.baby-beamup.club/oneVideoIdSameAsMetaId/meta/series/trvalue_1.json

**Comment by jaruba** [comment]
@TheBeastLT we can indeed reproduce this issue now in the Desktop app, while Android and Web seem to work fine with this test case.

thank you for reporting it

**Comment by TheBeastLT** [comment]
@jaruba Thanks, seems correct, though couldn't test in in the app as the previous cached response is used.

**Comment by jaruba** [comment]
@TheBeastLT you just need to uninstall the previous addon, the manifest link for the second test addon has a different URL path to avoid caching, but we reproduced it already:
![image (5)](https://user-images.githubusercontent.com/1777923/106004005-70a5d880-60bb-11eb-9036-ac5d32c0da3d.png)

**Comment by jaruba** [comment]
We have found the relevant code that is causing this inconsistency and are working on resolving it. We should hopefully manage to include the fix in the next release which will be within the next few weeks.
