### ISSUE TITLE
Pass custom http header to the player

### ISSUE THREAD

**Issue by ewwink** [Stremio/stremio-addon-sdk#145]
in Kodi I can use the `|` to set custom http header, for example

```
http://example/video.mp4|cookies=test_cookies&user-agent=fake_ua
```

can I use that with Stremio?

**Comment by krishne35** [comment]
When is this feature coming to android app ???

**Comment by sleeyax** [comment]
I don't think it's a feature yet, it's rather at the proposal stage right now...

**Comment by krishne35** [comment]
> I don't think it's a feature yet, it's rather at the proposal stage right now...

Ahhh it's implemented on desktop apps tho

**Comment by sleeyax** [comment]
@krishne35 oh is it? Never mind I didn't day anything!

**Comment by jaruba** [comment]
@ewwink @krishne35 please see the [Stream Response](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md) docs under `stream.behaviorHints.proxyHeaders`, this is available in both Desktop and Android versions.

**Comment by krishne35** [comment]
Thanks i have been using this paste month or so but cloudflare proxy is fast 

Idk why but with cloudflare proxy Android app keeps crashing with bigger HDR files 
Will try to grab some logs and report the issue
