### ISSUE TITLE
Search for subtitles without imdbid

### ISSUE THREAD

**Issue by ThanosDi** [Stremio/stremio-addon-sdk#147]
Is there a way to search for subtitles(from your plugin) without an imdbid?
For example to search providing videoHash, filename, season and episode?

**Comment by Ivshti** [comment]
@jaruba can help here

**Comment by jaruba** [comment]
@ThanosDi can you be a bit more specific?

`videoHash` and `filename` are passed to the subtitle addons, as the documentation states: https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/requests/defineSubtitlesHandler.md

you could also determine the name / season / episode for movies / series based on the filename, with a module such as [video-name-parser](https://www.npmjs.com/package/video-name-parser)

**Comment by ThanosDi** [comment]
Yeah sorry I wasn't so clear. I don't want to implement my own subtitle handler but use stremio's build in one(OpenSubtitles).
I noticed that if the stream has an imdbid (tt...) it will try to fetch subtitles automatically, but that's not the case the id is a custom one.

So is there a way to use the build in subtitle plugin without a imdbid?

**Comment by jaruba** [comment]
So u want to make requests to the official subtitle addon directly? 
You will first need to state that the project u are building is in relation to Stremio, otherwise I can't offer further assistance..
As we (the Stremio team) can only offer assistance for questions relating to Stremio, or otherwise Stremio approved 3rd parties.

**Comment by ThanosDi** [comment]
Well ofc I am building a project in relation to Stremio, how else I was gonna use all these info if not. 
I'm not sure what do you want me to provide you at this point since it's a WIP but when it's ready I'll add this as a Stremio 3rd party add on.

I previously built the Piratebay addon and won the 2018 competition but again I'm not sure what information you need from me.

My question is if I can utilize the OpenSubtitle plugin to fetch subtitles from within Stremio for a stream that doesn't have an imdbid but a custom id.

**Comment by jaruba** [comment]
A verbal agreement is fine. (which u did with ur last message)

We simply need to ensure that u are not building an application that is competing with Stremio directly. (without the explicit approval of the company behind Stremio)

Please join the unofficial community chat: https://discord.gg/zNRf6YF

And PM me there (I have the same username) as this is not a SDK related question. You can message me directly there for any other questions as well in the future.
