### ISSUE TITLE
Stremio Can't Load Stream by Provided infoHash

### ISSUE THREAD

**Issue by bigmouth-fringe** [Stremio/stremio-addon-sdk#151]
I'm trying to provide streams with infoHashes I fetched. Streams are recognized by Stremio and I can click on them, then stream icon glows indefinitely and nothing happens.

So far I checked infoHash validity and tried to load it using Transmission, works fine. What am I doing wrong?
Thanks.

UPD: So I waited long enough and got an "Failed to fetch" error

**Comment by bigmouth-fringe** [comment]
So I waited long enough and got an "Failed to fetch" error

**Comment by bigmouth-fringe** [comment]
Converting the infoHash to lower case solved my problem, closing the issue

**Comment by sleeyax** [comment]
I'm glad you found a solution, though now I wonder if this is the expected behaviour.

If infohashes should always be lowercase, maybe Stremio internals or the addon sdk should always convert it to lower instead of relying on the user to do this?

**Comment by Ivshti** [comment]
@jaruba sleeyax makes a good point here
