### ISSUE TITLE
Meta link for play/resume

### ISSUE THREAD

**Issue by imduffy15** [Stremio/stremio-addon-sdk#156]
Hi,

I would like to be able to trigger stremio to resume playing content on my androidtv via Alexa.

Looking at the APK I can see that there is a handler for `stremio://`

Is there a `stremio://` URL I can form from an IMDB ID that would result in that content:

 - Opening and resuming from where I left off with the last used stream
 - Or if no last used stream is present, use the same logic that auto play next episode uses for stream selection to start playing

**Comment by jaruba** [comment]
Hi, I'm afraid what you wish to do is not possible, there is no deep link that can lead to the video player directly.

If you wish to automate an android device, you may have more luck with interacting to automation apps directly, such as Tasker.
