### ISSUE TITLE
Export public types from @types/stremio-addon-sdk

### ISSUE THREAD

**Issue by victorgveloso** [Stremio/stremio-addon-sdk#157]
Example:

```typescript
export {};
export type ShortManifestResource = 'catalog' | 'meta' | 'stream' | 'subtitles' | 'addon_catalog';
export type Extra = 'search' | 'genre' | 'skip';
export type ContentType = 'movie' | 'series' | 'channel' | 'tv';
export interface Args {...}
export interface AddonInterface {...}
export interface Cache {...}
export interface MetaPreview {...}
export interface MetaDetail extends MetaPreview {...}
export interface MetaLink {...}
export interface MetaVideo {...}
```

When using typescript, I'd like to access Args, ContentType, AddonInterface, Extra, and ShortManifestResource.

**Comment by victorgveloso** [comment]
I think [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7ec78508c6797e42f87a4390735bc2c650a1bfd/types/stremio-addon-sdk/index.d.ts) belongs to @sleeyax.  Could you please apply this changes?

**Comment by sleeyax** [comment]
I believe `@types/stremio-addon-sdk` also isn't completely up to date with the latest stremio addon sdk spec. I think anyone including you @victorgveloso can update it on DefinitelyTyped. I'm currently busy with other things so feel free to do so.

Why do you need those types exported though? They work just fine as readonly's for my usecases thus far https://github.com/sleeyax/stremio-addons#info-for-developers.

**Comment by victorgveloso** [comment]
We shouldn't need to copy and paste that code fragment in order to use it. It should be like any other type definition: just `npm install ` it. When I try to use addonInterface it claims that some args type is not exported.

**Comment by sleeyax** [comment]
Of course you don't have to copy paste it. But I don't see in what use case you need the types exported as you can for example just call `addon.getInterface()` in your code and it will be typed.

Only reason I see you'd want this is to extend the `AddonInterface` type etc, but following the addon sdk spec there shouldn't be a reason to do so.

Can you give an example of how you would use the exported types to help  me understand your use case?

**Comment by victorgveloso** [comment]
[This](https://github.com/victorgveloso/MicoLeaoDubladoAPI/blob/main/src/HttpServer.ts) is an example. I want to use AddonInterface as a parameter type, but `import { AddonInterface } from '@types/stremio-addon-sdk'` fails due to AddonInterface not being exported. The same thing happens to the other mentioned types: ShortManifestResource, Extra, ContentType,  and Args. Import those types might be optional, but I want to and can't (because they aren't exported)

**Comment by victorgveloso** [comment]
Some functions you defined in [your project](https://github.com/sleeyax/stremio-addons#info-for-developers) doesn't have typed arguments (e.g. https://github.com/sleeyax/stremio-addons/blob/master/packages/addons/watchcartoononline/src/addon.ts#L11). If you were using strict configs for typescript, it should at least raise a warning because it is implicitly typing it as `any`.

**Comment by sleeyax** [comment]
Oh I see now. I didn't take into account more advanced use cases like this.

**Comment by victorgveloso** [comment]
PR merged into master. Thank you @sleeyax !
