### ISSUE TITLE
Is there any way to get infoHash through the handlers?

### ISSUE THREAD

**Issue by graphen007** [Stremio/stremio-addon-sdk#163]
Hi! - I was wondering if there is any way to extract magnet url or infoHash from the addon handlers? I cannot seem to find it.

**Comment by jaruba** [comment]
Hi, if you are asking if you can get the infoHash of what a user has requested to watch, than the answer is no, the stream handler responds with streams, this is the last addon request made until the user starts playback, what the user chose is not sent to any addon
