### ISSUE TITLE
Spec: addonSettings (http transport)

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-addon-sdk#17]
be able to specify `manifest.addonSettings` as an array of `{name, description, type, headerName, isRequired}`

That would allow every add-on to have add-on specific settings, that will be passed to it as HTTP headers in the case of the http transport (it will be supported only on the http transport)

Use cases:

- Add-ons with authentication - e.g. put.io
- Add-ons that require specific user preferences (e.g. "HD only") 

Kind of related to: https://github.com/Stremio/stremio-addon-sdk/issues/15 - this is an implementation example of a similar thing, although the preferences are in the URL; it will be easy to extend this example to this spec

**Comment by jaruba** [comment]
Closing this issue in favor of: https://github.com/Stremio/stremio-addon-sdk/issues/125
