### ISSUE TITLE
Addon request

### ISSUE THREAD

**Issue by Light7654** [Stremio/stremio-addon-sdk#170]
If possible Please add

Dopebox - https://dopebox.to/
Yesmovies - https://yesmovies.mn/
Fmovies(new one) - https://fmovies.app/

**Comment by jaruba** [comment]
@Light7654 sorry, the community creates the addons, not the Stremio team

**Comment by Light7654** [comment]
Ohh so how can I contact with community

**Comment by sleeyax** [comment]
@Light7654 r/StremioAddons on reddit (you could also join the discord from there)

**Comment by Light7654** [comment]
Ohh...kay thanku
