### ISSUE TITLE
VLC-like brightness and volume gestures in Stremio's player

### ISSUE THREAD

**Issue by wisdomtooth** [Stremio/stremio-addon-sdk#175]
Not sure if this is the right suggestion box, but... Changing volume and, especially, brightness with a movie on full screen is a bit clunky using standard mobile controls. VLC has great gestures for them sliding thumbs up and down on both sides of the screen. Any chances of having them on Stremio's player too?

I had it on dial in Stremio bc of the lack of screen fitting on its player, and was glad to revert back to Stremio's when that feature was incorporated, but the lack of gestures may push me back to using VLC again.

**Comment by jaruba** [comment]
Hi, feature requests go here: https://github.com/Stremio/stremio-features

And bug reports go here: https://github.com/Stremio/stremio-bugs

**Comment by wisdomtooth** [comment]
> Hi, feature requests go here: https://github.com/Stremio/stremio-features

The intro there says it's for the desktop app only.
