### ISSUE TITLE
New event ?

### ISSUE THREAD

**Issue by michalss** [Stremio/stremio-addon-sdk#183]
Hi is there possible to make a new event or endpoint to check when video is on its end ? I would like to implement Trakt and fo that i need to know when stream is done.

Regards

**Comment by jaruba** [comment]
Stremio already supports Trakt scrobbling, you can set it up in the settings of the desktop / android mobile app and also in the user dashboard at: https://stremio.com/login (under Integrations)

**Comment by jaruba** [comment]
But to answer ur question, player playback events are not supported, and may also be considered a privacy issue.

The closest thing to a playback event is the subtitles resource request, which presumes that the user started playback of the item, but no progress or ended events..

**Comment by jaruba** [comment]
Official integrations (such as Trakt) and official addons (such as the OpenSubtitles addon) all require the use of an IMDB ID as the metadata object ID.
