### ISSUE TITLE
BitTorrent2IPFS.

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [Stremio/stremio-addon-sdk#204]
https://github.com/riffcc/torrent2ipfs/

torrent2ipfs is a BitTorrent to IPFS bridge. It takes torrent files, downloads them with a torrent client and then adds the downloaded content to IPFS.

Requires IPFS, Python3, qBittorrent.

torrent2ipfs will add all torrents from ingest/ to qBittorrent with a special tag, then monitor qBittorrent until it no longer has any torrents to download. It will create IPFS hashes for each torrent you added, storing them as a JSON file. It's smart enough to skip creating IPFS hashes for torrents it has already processed before.

test.torrent is included for testing, which is actually ubuntu-20.04.4-live-server-amd64.iso.torrent

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://github.com/ipfs/awesome-ipfs

There are various projects that might be able to shed some more clarity on the matter.

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://github.com/Netflix/p2plab

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://youtu.be/wNfk05D887M

**Comment by jaruba** [comment]
@OpenOS-Project-Creator-Founder But the initial project you linked is not pitching IPFS protocol support, it pitches automated uploads to IPFS from the torrent network, which if done from the user's device is considered an invasion of privacy. (and maybe even a security issue)

We know exactly what IPFS is, its benefits, and we have experimented with it in the past (years ago), as we have always tried to implement cutting edge technologies to improve performance and increase efficiency. I think Stremio might even still support static addons from the IPFS network. With that said, our prior experiments have proven that IPFS was not yet mature enough, and interest in this technology from a community addon developer perspective seemed to be slim to none, with a learning curve too.

I believe that `torrent2ipfs` is outside the scope of the Stremio project, and the IPFS technology has not been widely adopted yet, until it will be, it adds no benefits to Stremio.

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://blog.ipfs.tech/2021-05-05-audius-uses-ipfs-web3-video/

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://github.com/ZorrillosDev/watchit-app

**Comment by jaruba** [comment]
@OpenOS-Project-Creator-Founder I hope that you realise that Stremio is not a content provider, and cannot make use of video streaming delivery methods. Stremio does not provide any content, the community addons provide the content.

**Comment by OpenOS-Project-Creator-Founder** [comment]
Yes though if implemented correctly everyone can host categories or content or entire studios library or allow for better Peario Party Streaming to take place.


If Stremio added IPFS into itself it would make it easier for addons to interact with IPFS.

Stremio can act as a gateway of sorts.

https://docs.ipfs.tech/concepts/ipfs-gateway/
