### ISSUE TITLE
Reading playback state of Stremio

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [Stremio/stremio-addon-sdk#205]
I'm planning on writing an addon that sync services like MyAnimeList like how Taiga or Trackma works. Is there a way to read what the user is currently watching and how much they progressed through the media?

**Comment by jaruba** [comment]
Hi goddess, as a fellow weeb I can sympathize with your efforts, so I will assist within the boundaries of possibility.

The bad: Although we have had an increasing demand lately for playback tracking events, this is not yet possible. The only tracking addon is Trakt, which is an official addon and works with the help of internal app functionality, such functionality is not exposed to community addons though. We might consider adding such events for community addons too, but we cannot give an ETA at this time.

The good: There is one "hack" that can be used for basic functionality, it was used in the past for a local addon that was handling Discord status updates. You would have to create a subtitles addon, and simply respond with no subtitles to the subtitles request. A subtitle request will be done at the start of playback for any movie or episode and will pass the IMDB (or Kitsu if that is what is used) ID. If you are fine with presuming that all videos that have been started have also been finished, this would be a (very basic) way of starting work on such an addon. You might face issues mapping IMDB or Kitsu to MAL ID (or other IDs for anime specific content), something that I could suggest is downloading [this map](https://1fe84bc728af-stremio-anime-catalogs.baby-beamup.club/map.json), which maps mal / anilist / anidb to kitsu id, it could easily be reversed to find mal id from kitsu id, and the map updates every few hours or so, this will not help to map imdb id to something else though, but it should be a good start.

The gift: The addon that creates the aforementioned map is an experimental addon i built some time ago and never publicly released, but given your interests i will share it with you also, just [click this link](https://1fe84bc728af-stremio-anime-catalogs.baby-beamup.club/configure)

I will keep you updated regarding the availability of the playback tracking feature for community addons.

**Comment by EmiliaTheGoddess** [comment]
That makes sense. Thanks for the information! I'll try making it with the hack. I'm also looking forward to the updates in future. I'm sure Stremio's future is bright. Take care!
