### ISSUE TITLE
Request: make it possible to set default subtitles size for a stream

### ISSUE THREAD

**Issue by fedew04** [Stremio/stremio-addon-sdk#208]
I made an addon which adds a series. The episodes from the series stream mkvs from torrents, which include subtitles in them. However, for the correct viewing experience, the subtitles need to be at 160% size, since there is a lot of typesetting which gets messed up when the size is not 160%. Is there any way to make it the default subtitle size for these streams? If not, I would very much appreciate if this option was added to the SDK (maybe it could be a property of the subtitle object?), Thanks.

**Comment by jaruba** [comment]
There is no way, and imho there should not be.. community addons should not have the ability to set a default subtitle size, that would overwrite the user's choice on some platforms.
