### ISSUE TITLE
Manage Subtitles Add-on

### ISSUE THREAD

**Issue by lowlevel-1989** [Stremio/stremio-addon-sdk#235]
Why doesn't my add-on appear in the community? It's been two weeks since I submitted it; is there a way to check its status?

Add-on ---

Manage Subtitles is an add-on for Stremio that allows you to manage your subtitles or follow the subtitles of other users completely free of charge.

manifest: https://addons.lowlevel1989.click/conf/api/v1/manifest.json 

dashboard: https://addons.lowlevel1989.click

**Comment by dexter21767-dev** [comment]
did u use the stremio addon sdk in your addon? if so did u use the [publishToCentral](https://github.com/Stremio/stremio-addon-sdk/tree/master/docs#publishtocentralurl) to actually send your addon's manifest to stremio community addons? 
Alternatively, u can just use [this website](https://stremio.github.io/stremio-publish-addon/index.html) to do it manually.

**Comment by lowlevel-1989** [comment]
> did u use the stremio addon sdk in your addon? if so did u use the [publishToCentral](https://github.com/Stremio/stremio-addon-sdk/tree/master/docs#publishtocentralurl) to actually send your addon's manifest to stremio community addons? Alternatively, u can just use [this website](https://stremio.github.io/stremio-publish-addon/index.html) to do it manually.

Yes, that's what I've done. I manually uploaded the 'manifest.json' file to the website, but it's been more than two weeks, and I can't verify its status.

**Comment by dexter21767-dev** [comment]
to verify the status just go to any stremio app and go to the community addons and search for your addon, it's already there.
