### ISSUE TITLE
Question: Stream Object doc

### ISSUE THREAD

**Issue by tymmesyde** [Stremio/stremio-addon-sdk#25]
Hello !
I wanted to know how to display more information about a stream (quality for example) rather than placing it in the title like on the Zooqle add-on.
![screenshot_70](https://user-images.githubusercontent.com/7889816/48247697-99672800-e3f4-11e8-8e32-52967921a055.png)
It seems that the `tag` array doesn't show anything on the stream.

**Comment by Ivshti** [comment]
This addon still uses the title, but also cleverly uses new lines and emoji to achieve this effect.

**Comment by tymmesyde** [comment]
Oh very nice thank you !
