### ISSUE TITLE
Addon won't load on Android/Fire TV: "The content did not load, error occured"

### ISSUE THREAD

**Issue by diridevelops** [Stremio/stremio-addon-sdk#250]
Hi,
I'm following the Quick Example section in the readme and also added the basic catalog from the [docs](https://stremio.github.io/stremio-addon-guide/sdk-guide/step2).
After I do `node ./addon.js` or `npm start` I'm able to install the addon on the web Stremio and it's showing the catalog correctly. But when trying to see the catalog on Android TV it appears a notification saying "The content did not load, error occured".
Any clues why this may be happening?

**Comment by TRtomasz** [comment]
It does not have a certifiacate installed, you must be running on https to make it possible to install addon on a remote device.

**Comment by diridevelops** [comment]
Even if my Android TV is on the same network? So there's no way to test the app there?

**Comment by diridevelops** [comment]
> It does not have a certifiacate installed, you must be running on https to make it possible to install addon on a remote device.

Even if my Android TV is on the same network? So there's no way to test the app there?
