### ISSUE TITLE
Question: How do I load a youtube link in my add-on

### ISSUE THREAD

**Issue by AlecMcCutcheon** [Stremio/stremio-addon-sdk#252]
Tried just adding the URL but it seems that didn't end up working very well, trying to link into a youtube live stream that's constantly running on youtube, and i know that with the youtube addon you can load youtube videos, i just don't know how to accomplish that in my addon, or even somehow hook into the youtube addon in order to play the live stream.

**Comment by dexter21767-dev** [comment]
yes, u can return a `ytId` instead of a url. [check this part of the documentation](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md#stream-object).
