### ISSUE TITLE
Exploring Possibilities in User Interaction with Stremio's Catalog

### ISSUE THREAD

**Issue by nissindiaz** [Stremio/stremio-addon-sdk#253]
Dear developers,

I hope you are all doing well! I would like to start a conversation about the opportunities to explore user interaction with Stremio's catalog, especially regarding unlocking links from other cloud storage sources, beyond Torrents.

We are all aware of the richness of content that Stremio offers, but we know that there is a variety of cloud storage sources that may not be fully integrated. The question is: is it possible and feasible to work with user interaction responses from Stremio's catalog to unlock links from other sources? For example, in a media source correctly configured with movie and series IDs and URLs, only after the user interacts with a specific movie (e.g., a click), the event to unlock the link is triggered (via the bridging services' API) to avoid unlocking all other media that the user hasn't even clicked on.

If anyone has experienced this or has ideas on how to approach this challenge, please share your experiences and thoughts. Thank you for your participation, and I look forward to your contributions.

**Comment by jaruba** [comment]
it sounds to me like you are talking about "URL resolving", which is the requirement of some APIs to convert an ID or code to a streamable URL.
as Stremio addons are practically HTTP servers, the way to do this is by serving a URL in the `streams` response that points back to the Stremio addon server with the required code, the Stremio client's video player will then request the stream which connects back to the addon server, the addon server now resolves the URL for the player then uses HTTP header redirect to point to the resolved URL, Stremio's player will follow the redirect and initiate playback

**Comment by nissindiaz** [comment]
I'm facing an issue while trying to unlock links using the AllDebrid API in the addon's hosting environment. I'm using Vercel. It seems that the API recognizes requests from Vercel as originating from a VPN, leading to blocks or failures in the unlocking process. I would like to request your assistance to better understand this problem and explore possible solutions or guidance on how to work around this issue in the specific context of addon hosting or any other solution.

**Comment by nissindiaz** [comment]
I'm facing an issue while trying to unlock links using the AllDebrid API in the addon's hosting environment. I'm using Vercel. It seems that the API recognizes requests from Vercel as originating from a VPN, leading to blocks or failures in the unlocking process. I would like to request your assistance to better understand this problem and explore possible solutions or guidance on how to work around this issue in the specific context of addon hosting or any other solution.
