### ISSUE TITLE
Stremio and Debrid services addon

### ISSUE THREAD

**Issue by nissindiaz** [Stremio/stremio-addon-sdk#255]
Dear Developers, regarding the integration of Stremio with debrid services, I'm facing an issue when trying to unlock links using the AllDebrid API in the addon's hosting environment. Locally, I can select an item from the catalog and play it with the unlocked URL. However, in the hosting environment, the API recognizes requests from the server as originating from a VPN, leading to blocks or failures in the unlocking process. I would like to seek your assistance in understanding this problem better and exploring possible solutions or guidance on how to work around this issue in the specific context of addon hosting or any other solution.

**Comment by TRtomasz** [comment]
your server should have unique IP not shared one they perhaps you will be fine.

**Comment by dexter21767-dev** [comment]
if your server isn't getting a unique IP, maybe u can try using a proxy to get a unique IP.
