### ISSUE TITLE
Displaying addon error messages?

### ISSUE THREAD

**Issue by SageTendo** [Stremio/stremio-addon-sdk#256]
Does the SDK provide a way of displaying error responses or messages from an addon within Stremio?

**Comment by jaruba** [comment]
what app are u testing with? (on what platform) and can you explain the issues you're experiencing with it?

**Comment by SageTendo** [comment]
I'm currently developing an addon that will make use of MyAnimeList's (MAL) API. For convenience purposes, I'd like to display a message to the user when their MAL API key has expired within Stremio. I was wondering if there was a way of achieving something of that sort.

**Comment by jaruba** [comment]
There is no guaranteed way of showing a notification to the user across all platforms. I guess the closest thing that could be done is replying with a stream and externalUrl pointing to the addon config page. But the users may never see it if it's at the end of a big stream list..

**Comment by jaruba** [comment]
the MAL API refresh token can be renewed within 31 days though? so giving such a notification would be for an edge case where a user didn't use the addon for 31 days?

**Comment by SageTendo** [comment]
> There is no guaranteed way of showing a notification to the user across all platforms. I guess the closest thing that could be done is replying with a stream and externalUrl pointing to the addon config page. But the users may never see it if it's at the end of a big stream list..

I guess I could look into that and see how effective it might be. Thank you.

**Comment by SageTendo** [comment]
> the MAL API refresh token can be renewed within 31 days though? so giving such a notification would be for an edge case where a user didn't use the addon for 31 days?

That's a fair point, I guess I just got caught up in the "what ifs". I'll close this issue, thanks.
