### ISSUE TITLE
Hi stremio I need your help to add sites for me to watch Arabic works through Stremio.  I do not know anything about the programming language. I hope that the team specialized in creating add-ons in Stremio will create an add-on that supports Arabic and Turkish businesses.  I have collected the best sites for watching Arabic works with this link    I hope that my request will be responded to. I tried to create an addition, but I cannot do so due to my lack of experience in the programming language.  Thank you .

### ISSUE THREAD

**Issue by Ziad8a** [Stremio/stremio-addon-sdk#267]
![image](https://github.com/Stremio/stremio-addon-sdk/assets/105057359/b889d45d-d382-4958-8c29-362f3c24f278)

**Comment by Ziad8a** [comment]
**Arab Torrent**

https://arab-torrents.net
https://www.arab-torrents.com
http://arabscene.org
https://arabicsource.net
https://www.arabp2p.net
http://arabscene.me

https://turktorrent.us
https://torrent-turk.de

**Comment by dexter21767-dev** [comment]
@Ziad8a stremio team doesn't make addons, the community does.
u might have better luck asking here https://www.reddit.com/r/StremioAddons/
