### ISSUE TITLE
Invalid addon publish - too many addons published. Please try again later error.

### ISSUE THREAD

**Issue by svetlozardraganov** [Stremio/stremio-addon-sdk#274]
I'm getting the following error when trying to publish my addon from the UI:
https://stremio.github.io/stremio-publish-addon/index.html

![image](https://github.com/Stremio/stremio-addon-sdk/assets/74985932/bf347142-68af-4946-8dd0-22ef586f7c70)

Tried multiple times but always got this error.

I'm able to find my addon in the following list. Does this mean the addon is successfully published?
https://[api.strem.io/addonscollection.json](https://api.strem.io/addonscollection.json)

The addon is not available in the community addon list:
https://stremio-addons.netlify.app/

I'm also getting the following error when using publishToCentral() function in my code:

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by svetlozardraganov** [comment]
Found the following page for submitting unofficial addons:

https://github.com/danamag/stremio-addons-list/issues/new?assignees=&labels=misc&template=submit-addon.yaml&title=Addon+Name

And made a request to include my addon to the list:
https://github.com/danamag/stremio-addons-list/issues/334

**Comment by jaruba** [comment]
the initial publish link you pasted is for Stremio's internal addon catalog, which only allows to publish 1 addon every 24h, this is because this endpoint has been abused in the past by bad actors that spammed the addon list with duplicate many duplicate addons, so we had to drastically rate limited it
