### ISSUE TITLE
Feature Request: Update Addon URL

### ISSUE THREAD

**Issue by Nitzantomer1998** [Stremio/stremio-addon-sdk#281]
Hi,

I would like to request a feature that enables an addon owner to update their base URL, for reasons such as changing the host server.

Currently, without the ability to update the base URL, changing a host server causes significant issues for users of the old addon. They would have to search for and install the new version, which is inconvenient and frustrating.

I suggest implementing a special URL with authentication, allowing the addon owner to update the base URL. This would streamline the process and ensure a smoother experience for users.

**Comment by jaruba** [comment]
you need to increase the addon version from the addon manifest, then publish ur new addon url (to the addon list in the apps), and finally make ur old addon server inaccessible 

this will replace the addon url for all ur users, but it only works if both the old addon url and new addon url were published to the addon list in the apps, if both addons have the same id in the manifest, and if the addon from the new server has an increased addon version compared to the old addon url
