### ISSUE TITLE
Request for Adding Custom Subtitle Language Support

### ISSUE THREAD

**Issue by Nitzantomer1998** [Stremio/stremio-addon-sdk#284]
Hi,

I have a subtitle addon called "Heb Subs," and I have set the subtitle language to a custom value, for example, "Test." Currently, all the subtitles provided by my addon are labeled as "Test."

It would be amazing if there was a way to add this custom language to the Stremio language settings. This would enable users to set "Test" as the default subtitle language within Stremio, just like the other predefined languages.

Thank you for considering this feature request!

**Comment by TRtomasz** [comment]
whats the purpose of this? Whe just not use regular subtitles language?

**Comment by Nitzantomer1998** [comment]
I want to separate two cases.

case number 1 the subtitles are made by man therefore they are good so they will be in the original language

but case number two when the subtitle is made by a translation from another language (by machine) so it’s less accurate/good so I want it in other label so it’s won’t mix the two

**Comment by jaruba** [comment]
@Nitzantomer1998 your request is simply not possible to achieve, the language list in the app settings is hardcoded, the app cannot know the custom languages that subtitle addons set before they respond to a movie / episode subtitle request
