### ISSUE TITLE
Access for video path or url i SubtitlesHandler

### ISSUE THREAD

**Issue by juhacz** [Stremio/stremio-addon-sdk#285]
I would like to create a plugin that downloads subtitles from the largest Polish subtitle database napiprojekt.pl. The problem is that in SubtitlesHandler I only have access to the OpenSubtitles videoHash, videoSize and filename fields. The problem is that "OpenSubtitles file hash" give me nothing to calculate the hash for napiproekt.pl. I need to read the first 1MB of the file, so I need the url to the file or access to it. Is it possible to gain such access to the video file to obtain the appropriate data?

**Comment by TRtomasz** [comment]
How do you expect to access video file that is locally on user side? Stremio provides the OS hash so addons can match it.

**Comment by juhacz** [comment]
I meant the url of the file from the web, debrid etc. or the path to the local file that the user opened. I just need to have access to it to create a hash and look for subtitles. What do you mean by "OS hash"? Can you provide a link to the documentation, I don't really understand what you mean?

**Comment by TRtomasz** [comment]
https://trac.opensubtitles.org/projects/opensubtitles/wiki/HashSourceCodes

**Comment by juhacz** [comment]
Of course I saw it, the value is passed to the StreamHandler. 

```
stdClass Object
(
    [type] => series
    [id] => tt8772296:1:1
    [extra] => stdClass Object
        (
            [videoHash] => 76956e15cafbe0c2
            [videoSize] => 949788100
        )

)
```

But how do I know that the one transferred corresponds to which of the several dozen thousand files on the napiprojekt website? Can I download them only by calculating the hash using the napiprojekt creators' method? How to associate the Opensubtiles hash with the napiprojekt hash?

**Comment by juhacz** [comment]
@TRtomasz can you answer my question? How can I calculate the hash of a file without having access to it locally? The OpenSubtitles hash is useless to me, I cannot convert it to the NapisProjekt hash. I have to calculate it myself, and this is only possible with access to the file. You probably know that this is our largest domestic subtitle service, it has everything there.
