### ISSUE TITLE
input free m3u from https

### ISSUE THREAD

**Issue by shp9595** [Stremio/stremio-addon-sdk#288]
is there an iptv addon where anyone can input free m3u playlist from https?  so we no need to input user and password

**Comment by jaruba** [comment]
this has nothing to do with the addon sdk

**Comment by shp9595** [comment]
> 

Thanks Jaruba, so we can not do anything or we still can make a new addon

**Comment by jaruba** [comment]
you asked if there is an addon X that does Y, we don't know what addons exist as they are made by the community developers

this repository is for the official SDK used to build addons, if u have a question about how to use the sdk if the documentation is not clear enough, or if you want to suggest new features for the sdk, then those are valid issues for this repository
