### ISSUE TITLE
Trying to use stremio:// protocol but getting error

### ISSUE THREAD

**Issue by mcspidey95** [Stremio/stremio-addon-sdk#293]
Hey, im working on a project that redesigns the new tab page on browsers. I added a feature where it opens the installed app version of stremio if its installed on the system through the protocol.

when i used stremio:// to open the app, it opens but gives me this error

![image](https://github.com/user-attachments/assets/2e7fd37a-116e-4b63-a6b4-8aadc7f94951)

how do i make the app open without triggering your fetch call?

**Comment by jaruba** [comment]
you mean deep linking? https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/deep-links.md

**Comment by mcspidey95** [comment]
i didnt know it was called deep linking. 

I just wanted to open the app, (the homepage)

thanks for the documentation link, i got what i needed 👍
