### ISSUE TITLE
Unable to add addon with Basic Auth

### ISSUE THREAD

**Issue by x0r3n** [Stremio/stremio-addon-sdk#297]
Hello. I try to add a addon with Basic Auth like https://username:password@addon.example.com/manifest.json but it won't fetch, if I open it in browser with username password pass to url it works, also It can fetch if I disable the basic auth, but I don't want to use it with out it. There are any solution to add it with Auth ?

**Comment by jaruba** [comment]
this is the correct way to gatekeep users: https://github.com/Stremio/stremio-addon-with-key
