### ISSUE TITLE
addon-sdk player behavior hints

### ISSUE THREAD

**Issue by anime-addon-testing** [Stremio/stremio-addon-sdk#299]
I have a custom add-on I'm using to stream a series provided in m3u8 , currently the behaviorHints.bingewatch parameter allows episodes to play one after another from the same source without me getting up which is great. I have intro/outro start/finish times for every episode and I want to skip it without touching the keyboard or mouse. I can fetch these times for every episode no problem just using them I cant. The add-on is for the desktop client and that's all I'm using at the moment.
I see a similar feature that's a WIP, though I don't think I need a playerHandler,. 
https://github.com/Stremio/stremio-addon-sdk/pull/241
Would it be possible for you to extend behavior hints to achieve a similar effect, skipping the first xxx seconds of the video and ending the video at xxx would also work - or is it already possible to do this some other way? again I have no idea how to implement it as I'm a complete novice, pointers are appreciated.

**Comment by dexter21767-dev** [comment]
stremio doesn't support this.
but u can manipulate the m3u8 to make it start the streams at xxx seconds 
https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming-23#section-4.3.5.2
