### ISSUE TITLE
WebSockets support

### ISSUE THREAD

**Issue by lndgalante** [Stremio/stremio-addon-sdk#301]
Is it possible to call a WebSocket to resolve to a [subtitle](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/subtitles.md) objects array within [builder.defineSubtitlesHandler()](https://github.com/Stremio/stremio-addon-sdk/tree/master/docs#builderdefinesubtitleshandlerfunction-handlerargs--) callback/handler function?

I tried this a few times without luck; I can get a subtitle object after ~10s, but then the subtitles icon doesn't appear on the Stremio Desktop app.

Context: I'm building a Subtitles service, and if the subtitle doesn't exists over my API/DB it will call a WebSocket server to index that movie or tv show subtitle live.

**Comment by jaruba** [comment]
this is not possible, the addon sdk works exclusively through HTTP(S)

maybe the solution for your issue is to respond with an empty subtitle array and download the subtitles in the background to cache them to disk for future requests?

**Comment by lndgalante** [comment]
@jaruba thanks for the reply.

Yes, that makes sense; what about doing a long POST instead of WS? I think I tried that but it didn't work, trying to think of any other alternative.
