### ISSUE TITLE
CLI: bootstrapper

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-addon-sdk#36]
`stremio-addon-sdk new` should bootstrap a new addon

other commands:

* validate: checks if the addon is behaving correctly by requesting the manifest and a few simple resources
* replicate: can be used to replicate to a directory or to IPFS, or to fuzz/lint the addon
* deploy: deploys to nowsh/lambda, tests if the addon is available (by running basic `detectFromURL` and checking a few resource paths), publishes to stremio central

the replicator being built in is fantastic, since replicating an addon is a combo of fuzzing, linting and replicating
validate/replicate can use the same code (the replicator), but configured differently
see https://github.com/Stremio/labs/issues/14

The CLI should be usable both in stremio addon projects (in the directory), and for addons that are not using the SDK (e.g. implemented in Go)

**Comment by shteryana** [comment]
Bootstrapper is now completed 

Replicator handled in a separate issue - https://github.com/Stremio/stremio-addon-sdk/issues/69
