### ISSUE TITLE
look into .ga domains for deploying

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-addon-sdk#59]
that might be a nice free option for a domain to use with Cloudflare when deploying addons

**Comment by jaruba** [comment]
I'm closing this, making .ga domains is now part of the deployment docs.

Some things to note:
- you can only register free domains for 1 year, after that they either get closed down or you need to pay for them
- free domains are only free if they have more then 4 characters in their name, 4 characters or less with the same domain extension can cost absurd sums (like $1000)
- free domains come from Freenom that made deals with third world countries to sell (or give for free) their domain extensions, their profit comes from what was mentioned in the above 2 points
