### ISSUE TITLE
Docs: Tutorials on making add-ons in different languages/stacks

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-addon-sdk#6]
Tutorials like:

- Create a hosted add-on with NodeJS
- Create a hosted add-on with Python
- Create a hosted add-on with Go
- Create a hosted add-on with PHP
- Create a hosted add-on with C#

Perhaps Tomek can help here as well

**Comment by Ivshti** [comment]
keep in mind this is part of the docs but not necessarily part of the SDK - as for most languages mentioned here it means making an add-on WITHOUT the SDK

**Comment by jaruba** [comment]
Node.js Example (without SDK, uses Express and static files):

https://github.com/Stremio/stremio-express-addon-example

PHP Example:

https://github.com/Stremio/stremio-php-addon-example

**Comment by jaruba** [comment]
Node.js Example (without SDK, uses Express, based on [addon-helloworld](https://github.com/Stremio/addon-helloworld)):

https://github.com/Stremio/addon-helloworld-express
