### ISSUE TITLE
Why are mjpeg streams failing to reproduce?

### ISSUE THREAD

**Issue by domingosl** [Stremio/stremio-addon-sdk#63]
I'm trying to reproduce a mjpeg stream of images to Stremio, the stream works fine on the browser and in Stremio you can see something is getting downloaded in the console, but the player refuses to play. Here's the code I'm using: https://github.com/gluxon/node-mjpeg-server

Here's a video showing how the browser handles the stream correctly, and then how it behaves on Stremio web app (same result on Desktop): https://streamable.com/olo82

**Comment by jaruba** [comment]
any chance we can get the add-on url to test with? or maybe some test code to be able to reproduce it?

**Comment by domingosl** [comment]
Yes of course, you can see my test stream at: https://disgustingrapidquadrants--five-nine.repl.co/video

But first, you need to lunch (click run) the test server at: https://repl.it/repls/DisgustingRapidQuadrants

**Comment by jaruba** [comment]
i ran the test server, test stream still doesn't work

**Comment by jaruba** [comment]
oh, the test urls are temporary, for me it was: `fastagitatedscientificcomputing`

**Comment by jaruba** [comment]
I can't find one web player that plays mjpeg, i tried videojs from:
https://codepen.io/anon/pen/WmWyrV

and this player from videku:
http://www.videku.com/play

All seem to act the same as Stremio, the players start loading the video, cache builds up, never plays and no error..

And it also seems that the browser itself doesn't treat it as a video type at all, it treats it like a image type.

When you go on the video url from your test code, you'll see that your browser isn't using the `<video>` tag to start playback like it normally does when presented with a video url, it's using a image container:

<img width="599" alt="Screen Shot 2019-03-26 at 13 08 49" src="https://user-images.githubusercontent.com/1777923/54992612-5df68000-4fc8-11e9-9ac1-0a047710ac84.png">

Given this scenario, I got to this page explaining things quite clearly:
https://stackoverflow.com/questions/37239869/mjpeg-html5-video-doesnt-stream-with-video

So I'm afraid we can't support mjpeg, as the `<video>` tag doesn't support it, and probably never will.

**Comment by domingosl** [comment]
Oh, that's too bad, I was planning on using mjpeg for my entry to the Stremio SDK contest. I think I have to create a video stream instead, in order to make it work. Thank you for pointing me in the right direction!

**Comment by jaruba** [comment]
I'm sorry if this came as an impediment to your project. It is unfair as MJPEG is considered a video compression format (unlike GIF which is considered a bitmap image format).

But as browsers chose to not support it in the `<video>` tag, there really isn't anything we can do about it..

**Comment by domingosl** [comment]
@jaruba I'de manage to find a way around by creating a video renderer! :) The project took more time than I anticipated because of this, but the end result is pretty good: https://github.com/domingosl/60-seconds-new-stremio

I hope it has winner potential for the Stremio SDK contest. Thank for your support.
