### ISSUE TITLE
Provide an alternative id for resource

### ISSUE THREAD

**Issue by TheBeastLT** [Stremio/stremio-addon-sdk#66]
It would be great to have ability to provide alternative id for resources to target multiple addons, which support different id schemes. 
Current use case is for anime addons, where we could provide a anime specific id and target anime specific addons, but also provide and imdbId based id and target the usual imdbId based addons.

**Comment by jaruba** [comment]
Can you be a little more clear about your request?

What do you mean by "alternative id for resources to target multiple addons, which support different id schemes"

Are you referring to alternative `resource` (meta, stream, catalog) or `type` (movie, series, tv, channel) here?

> Current use case is for anime addons, where we could provide a anime specific id and target anime specific addons, but also provide and imdbId based id and target the usual imdbId based addons.

I'm unsure what you mean here too, you can set `idPrefixes: ['something:', 'tt']` in your manifest, and your add-on will handle both such id requests.

**Comment by TheBeastLT** [comment]
I meant an alternative id for episodes/movies based on which stream providing addons are queried. 
so you could have something like
```
meta {
  videos: [
    { id: [ tt1111111:1:1, anime1], ... }
  ]
}
```
Then you could get stream from addons which support ` tt1111111:1:1` id and stream from addons which support `anime1` id.

**Comment by jaruba** [comment]
I'm not sure if this is needed, it works in reverse. Your add-on can have `idPrefixes: ['anime', 'tt']`, and it will get stream requests for both of the id types, thus responding to both of them.

Is there a reason why setting multiple ids to a stream is better then setting multiple ids in an add-on's `idPrefixes`?

**Comment by TheBeastLT** [comment]
It would enable you to get stream entries from addons which you can't control, but which support imdbId and you have a direct mapping for it.

**Comment by jaruba** [comment]
Ok, i think i understand where you're going with this, but i don't consider it being something that we should implement

Consider this scenario:
- an add-on has `idPrefixes: ['anime', 'tt']`
- a different add-on passes `stream { id: ['anime1', 'tt1111111:1:1'] }`
- this will lead to stream duplication from the same add-on

Besides, i still think it's not needed, `idPrefixes` can be used to an extent, and if an add-on wants results for streams from multiple stream id patterns, then it can make a separate add-on that gets `tt` requests, proxies other add-ons that support `tt` and responds to `anime` stream IDs. Alternatively, even the initial add-on (without making a separate add-on) can proxy these requests too.

So there is no limitation here that I can see, devs can still do what you're asking by proxying other add-ons, or making a separate add-on that acts like a middleware for id conversion and responses.

**Comment by TheBeastLT** [comment]
Yes I agree, that maybe it's a niche use case and can be achieved by the methods you've described. 

But it would also add complexity to the anime addons if they should support both ids, since they would need to proxy for id conversion and then most of the time imdb queries wont be for anime so these requests will be redundant.
The method of creating a proxying addon seems better, but it would use a predifined list of addons and not the user installed ones. And also since Stremio does not support async responses there would be a significant delay until all the responses are aggregated.

I'm closing this, since I partially agree that there's not a huge need for this, since it could be achieved in other ways.

Thanks!
