### ISSUE TITLE
Docs: publish an add-on using now.sh

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-addon-sdk#7]
Explanation/tutorial on how to publish an add-on with https://zeit.co/now - which btw is great for that purpose

**Comment by jaruba** [comment]
I started on this before my injury. Ran into an issue as `now`'s configuration file seems to ignore CORS atm.

I'll finish the docs for `now` but any add-on published there won't work in the web version unless they fix this.

**Comment by jaruba** [comment]
See: https://github.com/zeit/now-cli/issues/1431#issuecomment-402740101

**Comment by jaruba** [comment]
Further tests prove that the latest version of `now` works with changing header settings correctly.

https://github.com/Stremio/stremio-static-addon-example

Serves as the `Now.sh` and Github Pages example for static add-ons.
