### ISSUE TITLE
Can an addon written with addon-sdk manipulate video color etc?

### ISSUE THREAD

**Issue by fselcukcan** [Stremio/stremio-addon-sdk#74]
I would like to write an add-on for Stremio that makes anaglyph and/or stereoscopic experience on Stremio videos possible.

I plan to do this by
- duplicating video shown on same Stremio window one usually watch on Stremio and put them separated by an offset adjustable
- colorize videos differently, eg. left video red, right video cyan (ideally adjustable color)
- maybe tilt each of them around y-axis of the screen (ideally adjustable angle for each video)

Is that capability available to addon sdk?

**Comment by Ivshti** [comment]
no, the SDK cannot do that and it's out of it's scope

you should look into making your own server that's proxying the video and reencoding via ffmpeg
