### ISSUE TITLE
Subtitle not group by lang 

### ISSUE THREAD

**Issue by crstestacc** [Stremio/stremio-addon-sdk#75]
Group subtitle by lang not work or I do something wrong.

I try to pass array of object with url and lang like this
`const subsArr = [{url: url1, lang:'lang1'}, {url: url2, lang:'lang1'}]`
to `Promise.resolve({subtitles: subsArr })` but only one lang loaded. 
Also I try to use underscore and group by _.groupBy(array, 'lang') like opensubtitle do but than nothing loaded. Is there any sample code about this ?

**Comment by Ivshti** [comment]
Closing this since we can't reproduce

If you're still experiencing this and have a more complete example, feel free to reopen

**Comment by vmotta8** [comment]
In addition to the url and lang, it is also necessary to pass the id of each caption, for example:
```const subtitles = [{id: id1, url: url1, lang: 'lang1'}]```

Id added in the subtitles object at pr #154
