### ISSUE TITLE
Subtitles request without extra parameters fails

### ISSUE THREAD

**Issue by pedroslopez** [Stremio/stremio-addon-sdk#78]
When a subtitles request is made that doesn't contain any extra parameters, stremio sends us a URL like the following: `/subtitles/movie/tt1254207/.json`

This is in contrast to when you get things like videoHash, like so: `/subtitles/movie/tt1254207/videoHash=cfff08ce8455342c&videoSize=276134947.json`.

In the scenario where there are no extra parameters, we actually get a 404 on the server. This could be resolved by simply removing the trailing `/` character after the ID.

I found this can happen from Stremio when there's not a server running so it can't get the subhash or other times when it simply requests the subtitles without first waiting for the subhash to be returned (I see when it's a large file it hangs there and eventually the addons are queried for subtitles without a subhash, guessing because of a timeout of some sort)

**Comment by Ivshti** [comment]
We just found this issue last week. Next release (sometime this week) will contain a fix: https://github.com/Stremio/stremio-addon-client/commit/bb5f89dfa3ffaffecc2319832cb566349a230c44

**Comment by pedroslopez** [comment]
Wonderful!

I've also been having another issue with subtitles, specifically when returning them from the Stream object response. According to [the docs](https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/stream.md) you should be able to pass an array of subtitles along with the stream, but they don't seem to be showing up in stremio.

Specifying a stream object like this should work, correct?

`{ url: "[STREAM URL].mp4", subtitles: [{ url: '[SUB URL].vtt', lang: 'spa' }]  }`

**Comment by Ivshti** [comment]
it should work but I think it's not supported in the current version, please open a separate issue for this

I'll close this one and the next release should fix it
