### ISSUE TITLE
document addonCatalogs

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-addon-sdk#89]
Addons can now define addon catalogs, therefore extending the stremio addon catalog with new addons

this is implemented in stremio-core: https://github.com/Stremio/stremio-core/pull/97

it consists of adding a new field to the manifest (`addonCatalogs`) that behaves just like `catalogs` but catalogs there will be at `/addon_catalog` and will return `{ addons: [Descriptor }` 

Benefits are here: https://github.com/Stremio/stremio-core/issues/28

**Comment by jaruba** [comment]
Documentation was added with the following PR: https://github.com/Stremio/stremio-addon-sdk/pull/100
