### ISSUE TITLE
Not able to add series correctly

### ISSUE THREAD

**Issue by lai32290** [Stremio/stremio-addon-sdk#96]
I've added a TV series in Catalog format like bellow:

```
const CATALOG = [
    {
        id: "test_001:1:1",
        season: 1,
        episode: 1,
        type: "series",
        name: "My Test Series",
        poster: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg/220px-Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg',
        description: 'Pikachu!!!'
    },
    {
        id: "lai001:1:2",
        season: 1,
        episode: 2,
        type: "series",
        name: "My Test Series",
        poster: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg/220px-Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg',
        description: 'Pikachu!!!'
    }];
```

With stream list like this:

```
const STREAMS = {
    "lai001:1:1": {
        infoHash: "b9302d042f8f856d042e4c74e38cca6173c8b40e", fileIdx: 5
    },
    "lai001:1:2": {
        infoHash: "b9302d042f8f856d042e4c74e38cca6173c8b40e", fileIdx: 5
    }
};
```

But it's not being grouped in Stremio and streams are not found.

![image](https://user-images.githubusercontent.com/903193/68200957-a7b43980-ff9f-11e9-9442-49dbb2f56246.png)
![image](https://user-images.githubusercontent.com/903193/68200979-b39ffb80-ff9f-11e9-83bd-726865402442.png)

What's wrong in my code? how can I add a series?

**Comment by jaruba** [comment]
The "series" type does not work like the "movie" type. With the "movie" and "tv" types, the stream requests are made as soon as you access the Details page, but with the "series" and "channel" types, the Details page expects the `meta` to include the `videos` property, with an array of episodes of videos. When a video or episode is then selected, a stream request will be made for that episode or video id, instead of the meta id (like with "movie" and "tv")

Check the `videos` property on this page for more information:
https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/api/responses/meta.md

This is the intended behaviour, not a bug.

**Comment by lai32290** [comment]
It really works!! thank you so much!!

**Comment by lai32290** [comment]
@jaruba , I tried to separate by season, by id and `season` property like bellow, but it still appearing in the same list, like an only season.

```
        id: 'lai_001',
        type: "series",
        name: "My Test",
        poster: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg/220px-Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg',
        description: 'Pikachu!!!',

        videos: [
            {
                id: 'lai_0001:1:1',
                title: 'My test',
                released: new Date().toISOString(),
                episode: 1,
                season: 1
            },
            {
                id: 'lai_0001:2:1',
                title: 'My test',
                released: new Date().toISOString(),
                episode: 1,
                season: 2
            }
        ]
``` 

What is wrong in my configuration?

**Comment by jaruba** [comment]
This seems to be a bug, in order to show videos as episode you'll need to use `number` instead of `episode`.

Here is a working example:

```
builder.defineMetaHandler(function(args) {

    const videos = []

    const oneDay = 24 * 60 * 60 * 1000

    const now = Date.now()

    videos.push({
        id: 'lai_0001:1:1',
        title: 'My test',
        firstAired: new Date(now - oneDay).toISOString(),
        number: 1,
        season: 1
    })

    videos.push({
        id: 'lai_0001:2:1',
        title: 'My test 2',
        firstAired: new Date(now - (2 * oneDay)).toISOString(),
        number: 1,
        season: 2
    })

    return Promise.resolve({
        meta: {
            id: 'lai_001',
            type: "series",
            name: "My Test",
            poster: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg/220px-Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg',
            description: 'Pikachu!!!',

            videos
        }
    })
})
```

**Comment by lai32290** [comment]
That's cool! so the correct is `number` or `episode`? can I create a PR to updated the documentation?

**Comment by lai32290** [comment]
BTW, it's working to me, using the `number` property.

**Comment by lai32290** [comment]
Is this a bug for this node package or bug in `Stremio`?

**Comment by lai32290** [comment]
Oh Man, that's weird, it just stoped work again! 

```
const CATALOG = [
    {
        id: 'lai001',
        type: "series",
        name: "My video",
        poster: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg/220px-Pok%C3%A9mon_Detective_Pikachu_teaser_poster.jpg',
        description: 'Pikachu!!!',

        videos: [
            {
                id: 'lai001:1:1',
                title: 'aaaaa 1',
                released: new Date().toISOString(),
                number: 1,
                season: 1
            },
            {
                id: 'lai001:2:1',
                title: 'aaaaa 1',
                released: new Date().toISOString(),
                number: 1,
                season: 2
            }
        ]
    }
]
```

**Comment by jaruba** [comment]
It's a bug in Stremio, `number` was used before, it was supposed to be replaced by `episode` but it seems that creates this bug.

**Comment by lai32290** [comment]
Wow, that's bad, then I think there's nothing we can do, right? Anyway, thank you for help 😄

**Comment by jaruba** [comment]
It's not that bad, I'll look into fixing it in Stremio.

**Comment by lai32290** [comment]
I thought it could be my Stremio version, but I just checked, I'm in version `4.4.77`, so I think it's really a bug.

**Comment by jaruba** [comment]
I know, that's ok, you can use `number` safely, even when the bug will be fixed, Stremio will still have backward compatibility, so it will support `number` too.

**Comment by lai32290** [comment]
That's great, anyway, I can set both properties (`number` and `episode`) then it'll ensure always working.

**Comment by michalss** [comment]
This does not work :( I did try to use number but it puts all together into episodes...

**Comment by jaruba** [comment]
@michalss this is what the official addon "Cinemeta" currently uses for series:
<img width="633" alt="Screenshot 2022-08-31 at 10 23 04" src="https://user-images.githubusercontent.com/1777923/187618087-3da8d370-8b57-41bc-b0e2-b13b59cf3ab4.png">

so make sure to:
- set all episodes under the `meta.videos` array
- set both `video.episode` and `video.number` for backward compatibility
- make sure to set both `video.firstAired` and `video.released`
- make sure to set `video.id` and `video.name`

with all this done, and `meta.type` being set to `series`, i believe it should work as expected across all current Stremio apps

**Comment by michalss** [comment]
OK sorted, not sure why but if you included number it will brake it.. :)
