### ISSUE TITLE
How to get infoHash from magnets link or torrent file?

### ISSUE THREAD

**Issue by lai32290** [Stremio/stremio-addon-sdk#97]
When I opening the torrent source using `uTorrent`, it can show me the infoHash.
![image](https://user-images.githubusercontent.com/903193/68471997-44741280-01fe-11ea-9dcf-c34e9b634f59.png)

But if I have so many source to be added, the process to add torrent to uTorrent and get the hash from there might be a little bit annoy.

I googled about some tools to convert magnet links or torrent file to hash, but I couldn't find anything.

Is there a way to get the hash easier?

**Comment by jaruba** [comment]
With magnet links, this is very easy, let's take this ubuntu magnet link for example:
`magnet:?xt=urn:btih:326752e8b6549983b5d07bbc15a871f64d270c10&dn=Ubuntu+11+10+Install+Box&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740&tr=udp%3A%2F%2F9.rarbg.to%3A2730`

the part between `magnet:?xt=urn:btih:` and `&` is the infohash, in this case, it would be `326752e8b6549983b5d07bbc15a871f64d270c10`

With torrent files this is a bit more complex, torrent files are actually data files, they contain general data for the torrent (it's filelist, infohash, trackers, etc)

It is usually recommended to use Node.js to build add-ons, presuming you are using Node.js, you can use this package:
https://www.npmjs.com/package/parse-torrent

Which parses magnet links, local torrent files and remote torrent files, giving you whatever data can be extracted from it (this data will always include the infohash of the torrent too)

**Comment by jaruba** [comment]
Do you require any further assistance with this?

**Comment by lai32290** [comment]
I couldn't try it yet, but I believe your solution 😄 . I'll close this issue. Thank you so much!
